name: ci

on: [push, pull_request]

jobs:
  build-clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y ninja-build cmake clang clang-tidy clang-format lld g++
      - name: Configure (asan, clang)
        run: CC=clang CXX=clang++ cmake --preset asan -S .
      - name: Format check
        run: find src tests bench \( -name '*.h' -o -name '*.cpp' \) | xargs clang-format --dry-run --Werror
      - name: Build
        run: cmake --build build/asan -j
      - name: Test
        run: ctest --test-dir build/asan --output-on-failure
      - name: Bench
        run: cmake --build build/asan --target perf

  build-gcc:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'   # run on main, or change to a cron
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y ninja-build cmake g++ clang-tidy
      - name: Configure (asan, gcc; tidy off to avoid flag mismatch)
        run: CC=gcc CXX=g++ cmake --preset asan -S . -DENABLE_CLANG_TIDY=OFF
      - name: Build
        run: cmake --build build/asan -j
      - name: Test
        run: ctest --test-dir build/asan --output-on-failure
